### ISSUE TITLE
[connectivity_plus] MacOS build fails after adding package

### ISSUE THREAD

**Issue by woutervanwijk** [fluttercommunity/plus_plugins#329]
## System info

Issue occurs on: macOS
Plugin name: connectivity_plus_macos
Plugin version: 0.0.1
Flutter doctor output:

## Steps to Reproduce

1. When upgrading graphql from 5.0.0-nullsafety.5 to 5.0.0, connectivity_plus_macos 0.0.1 is included. This leads to the following build error, with no other changes in packages or code:

```
Launching lib/main.dart on macOS in debug mode...
lib/main.dart:1
/Users/code/test/macos/Pods/Reachability/Reachability.m:465:63: warning: cast to smaller integer type 'unsigned int' from 'Reachability *' [-Wpointer-to-int-cast]
                             NSStringFromClass([self class]), (unsigned int) self, [self currentReachabilityFlags]];
                                                              ^~~~~~~~~~~~~~~~~~~
1 warning generated.
/Users/code/test/build/macos/Build/Products/Debug/connectivity_plus_macos/connectivity_plus_macos.framework/Headers/connectivity_plus_macos-Swift.h:216:1: error: 'ConnectivityPlugin' has different definitions in different modules; first difference is definition in module 'connectivity_plus_macos.Swift' found return type is 'void'
+ (void)registerWithRegistrar:(id <FlutterPluginRegistrar> _Nonnull)registrar;
^
/Users/code/test/build/macos/Build/Products/Debug/connectivity_macos/connectivity_macos.framework/Headers/connectivity_macos-Swift.h:216:1: note: but in 'connectivity_macos.Swift' found different return type 'instancetype _Nonnull' (aka 'id')
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
^
/Users/code/test/macos/Flutter/GeneratedPluginRegistrant.swift:21:3: error: ambiguous use of 'register(with:)'
  ConnectivityPlugin.register(with: registry.registrar(forPlugin: "ConnectivityPlugin"))
  ^
/Users/wouter/.pub-cache/hosted/pub.dartlang.org/connectivity_macos-0.2.0/macos/Classes/ConnectivityPlugin.swift:20:22: note: found this candidate
  public static func register(with registrar: FlutterPluginRegistrar) {

                     ^
/Users/wouter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus_macos-1.0.2/macos/Classes/ConnectivityPlugin.swift:24:22: note: found this candidate
  public static func register(with registrar: FlutterPluginRegistrar) {

                     ^
/Users/code/test/macos/Flutter/GeneratedPluginRegistrant.swift:22:3: error: ambiguous use of 'register(with:)'
  ConnectivityPlugin.register(with: registry.registrar(forPlugin: "ConnectivityPlugin"))
  ^
/Users/wouter/.pub-cache/hosted/pub.dartlang.org/connectivity_macos-0.2.0/macos/Classes/ConnectivityPlugin.swift:20:22: note: found this candidate

  public static func register(with registrar: FlutterPluginRegistrar) {
                     ^
/Users/wouter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus_macos-1.0.2/macos/Classes/ConnectivityPlugin.swift:24:22: note: found this candidate
  public static func register(with registrar: FlutterPluginRegistrar) {
                     ^
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Analyzing workspace

```

**Comment by ductranit** [comment]
I have the same issue. Is there anyway to workaround this issue atm?

**Comment by mhadaily** [comment]
You mentioned `GraphQL` is that another package? if so, I guess we should send a PR to that package, can you please send me a link to the repo?

**Comment by ductranit** [comment]
@mhadaily I'm using this package https://github.com/zino-app/graphql-flutter

**Comment by woutervanwijk** [comment]
> You mentioned `GraphQL` is that another package? if so, I guess we should send a PR to that package, can you please send me a link to the repo? this seems to be a very old version of our package.

Already filed an issue there https://github.com/zino-app/graphql-flutter/issues/925

**Comment by woutervanwijk** [comment]
> I have the same issue. Is there anyway to workaround this issue atm?

Don’t upgradenI in my case :)

**Comment by mhadaily** [comment]
There is already a PR there https://github.com/zino-app/graphql-flutter/pull/913

I will follow up on their repo.

**Comment by fabiancrx** [comment]
@mhadaily your commented PR was not merged, but the `connectivity_plus` was bumped in this other PR https://github.com/zino-hofmann/graphql-flutter/pull/978. So I think this issue should be closed, as it should be fixed by now.

**Comment by mhadaily** [comment]
Thanks, it was fixed on this pr https://github.com/zino-hofmann/graphql-flutter/pull/978. I will close this
