### ISSUE TITLE
Build failed with   android_alarm_manager_plus:1.3.1

### ISSUE THREAD

**Issue by squallsama** [fluttercommunity/plus_plugins#493]
## System info

Issue occurs on: Android
Plugin name: android_alarm_manager_plus
Plugin version: 1.3.1
Flutter doctor output: 

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-x64, locale en)
    • Flutter version 2.5.1 at /Users/squall/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (2 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/squall/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/squall/Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/squall/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.6397.47

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • Pixel 5 (mobile)            • 192.168.0.170:39889       • android-arm64  • Android 12 (API 31)
    • iPhone 11 (Dmitry) (mobile) • 00008030-000D58100191402E • ios            • iOS 15.0 19A346
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 94.0.4606.61
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
```

## Steps to Reproduce

1. add `  android_alarm_manager_plus: ^1.3.1` to dependencies:
2. flutter pub get
3. flutter run

## Logs

```
/Users/wasd/development/flutter/.pub-cache/hosted/pub.dartlang.org/android_alarm_manager_plus-1.3.1/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AlarmService.java:139: error: cannot find symbol
            (Build.VERSION >= 23 ? PendingIntent.FLAG_IMMUTABLE : 0)
             ^
  symbol:   variable Build
  location: class AlarmService
/Users/wasd/development/flutter/.pub-cache/hosted/pub.dartlang.org/android_alarm_manager_plus-1.3.1/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AlarmService.java:228: error: cannot find symbol
            (Build.VERSION >= 23 ? PendingIntent.FLAG_IMMUTABLE : 0)
             ^
  symbol:   variable Build
  location: class AlarmService
```

**Comment by qcuong97** [comment]
i also have the same problem

**Comment by squallsama** [comment]
Folks, do you have any CI to check build success before merging Pull Request ? This bug was introduced in https://github.com/fluttercommunity/plus_plugins/pull/486

There should be additional import line:
`
import android.os.Build
`

**Comment by vbuberen** [comment]
Also found this issue and fixed it in my fork. Going to open a PR in ~20 minutes. There is not only missing import, but also wrong variable used to get Android version.
