### ISSUE TITLE
[device_info_plus] Not working with Flutter 2.8.0 on M1 Mac

### ISSUE THREAD

**Issue by ragokan** [fluttercommunity/plus_plugins#644]
## System info

Issue occurs on: iOS (M1 Mac)
Plugin name: device_info_plus
Plugin version: ^3.1.0
Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale
    en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.0)
[✓] VS Code (version 1.64.0-insider)
[✓] Connected device (1 available)
    ! Error: iPhone 13 is not connected. Xcode will continue when iPhone 13 is
      connected. (code -13)

• No issues found!
```

## Steps to Reproduce
1. Just upgraded Flutter and I got that error. I did all the clean, pod install, update things, nothing worked.
2. Error:
```
Launching lib/main.dart on iPhone 13 in debug mode...
lib/main.dart:1
Xcode build done.                                           26.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/ragokan/Projects/messageapp/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'device_info_plus' not found
    @import device_info_plus;
     ~~~~~~~^~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
Could not build the application for the simulator.
Error launching application on iPhone 13.
Exited (sigterm)
```

## Logs

```
...
             /Users/ragokan/Projects/messageapp/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'device_info_plus' not found
               @import device_info_plus;
                ~~~~~~~^~~~~~~~~~~~~~~~
               1 error generated.
...
```

```
➜  messageapp git:(master) flutter analyze
Analyzing messageapp...                                                 
No issues found! (ran in 3.0s)
```

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale
    en-TR)
    • Flutter version 2.8.0 at /Users/ragokan/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (18 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ragokan/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.64.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (1 available)
    • iPhone 13 (mobile) • 1388EFBD-5901-4C25-8AC6-ACA7E0F17894 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    ! Error: iPhone 13 is not connected. Xcode will continue when iPhone 13 is
      connected. (code -13)

• No issues found!
```

**Comment by justjew** [comment]
Same problem

**Comment by ragokan** [comment]
> 

I do think that the problem is instead resulted by **Flutter** itself. Because when I delete this package, I still get the error for another package.

**Comment by FeelHippo** [comment]
Having the same problem with device_info_plus: ^3.2.1 and Flutter 2.9.0-1.0.pre.464 • channel master.

@regokan, the issue is gone when I delete the package

**Comment by justjew** [comment]
The problem was on Flutter 2.8.0
2.8.1 has fixed it

**Comment by FeelHippo** [comment]
Thank you for your reply, justjew. 
I am on Flutter 2.8.1 • channel stable right now but still not working :/

**Comment by jiangxiaoqiang** [comment]
I am using 2.5.0 facing this error.
